name: Deploy to Azure VM (SSH pull)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key (known_hosts)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 -H "$SSH_HOST" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Test SSH
        run: ssh -o StrictHostKeyChecking=yes -T "$SSH_USER@$SSH_HOST" 'whoami && hostname'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

    