name: Deploy to Azure VM (SSH pull)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on:  ubuntu-20.04
    steps:
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/ .ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
    