name: Build and deploy to Docker hub
on:
  push: 
    branches: [main]

jobs: 
  push_to_registry:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.Docker_USERNAME}}
          password: ${{secrets.Docker_PASSWORD}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: manoj322/app:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
              sudo docker pull manoj322/hello-world:latest
              sudo docker stop hello-world || true
              sudo docker rm hello-world || true
              sudo docker run -d --name hello-world -p 80:5000 manoj322/hello-world:latest
